# ============================================================
#  FilmFeed - build videos.js from the Bunny upload record
#  Reads bunny_uploads.json + bunny_config.json and writes a
#  videos.js whose entries stream from your Bunny CDN (HLS).
#  Run this (or double-click build_feed_bunny.bat) after uploading.
# ============================================================
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

$cfg = Get-Content (Join-Path $root 'bunny_config.json') -Raw | ConvertFrom-Json
$cdn = $cfg.cdnHostname
if (-not $cdn) { Write-Host "ERROR: cdnHostname missing from bunny_config.json" -ForegroundColor Red; Read-Host "Enter to exit"; exit 1 }

$mapPath = Join-Path $root 'bunny_uploads.json'
if (-not (Test-Path $mapPath)) { Write-Host "ERROR: bunny_uploads.json not found. Upload clips first." -ForegroundColor Red; Read-Host "Enter to exit"; exit 1 }
$records = @(Get-Content $mapPath -Raw | ConvertFrom-Json)

# Same filename grammar as the original rebuild_feed: "Title (Year) ... - HH.MM.SS-HH.MM.SS.ext"
$re = '^(?<film>.+?) \((?<year>\d{4})\)[^-]*- (?<s1>\d{2})\.(?<s2>\d{2})\.(?<s3>\d{2})-(?<e1>\d{2})\.(?<e2>\d{2})\.(?<e3>\d{2})\.\w+$'

$entries = @()
foreach ($r in $records) {
    if (-not $r.guid) { continue }
    $name  = $r.file
    $film  = ($r.folder -replace '_clips$','')
    $year  = ''; $start = ''; $end = ''
    if ($name -match $re) {
        $film  = $Matches.film
        $year  = $Matches.year
        $start = "$($Matches.s1):$($Matches.s2):$($Matches.s3)"
        $end   = "$($Matches.e1):$($Matches.e2):$($Matches.e3)"
    }
    $entries += [pscustomobject]@{
        id    = $r.guid
        file  = "https://$cdn/$($r.guid)/playlist.m3u8"
        film  = $film
        year  = $year
        start = $start
        end   = $end
    }
}

$json = $entries | ConvertTo-Json -Depth 3
if ($entries.Count -eq 1) { $json = "[$json]" }
$banner = "// AUTO-GENERATED by build_feed_bunny - do not edit by hand.`n// Streams from Bunny ($cdn). Regenerate after uploading new clips.`n"
Set-Content -Path (Join-Path $root 'videos.js') -Value ($banner + 'const VIDEOS=' + $json + ';') -Encoding UTF8

$films = ($entries | Select-Object -ExpandProperty film -Unique).Count
Write-Host "Done. $($entries.Count) clips across $films films written to videos.js (streaming from $cdn)." -ForegroundColor Green
