# ============================================================
#  FilmFeed - build videos.js from the Bunny upload record
#  Reads bunny_uploads.json + bunny_config.json and writes videos.js
#  (HLS URLs streaming from your Bunny CDN). JSON is built by hand so
#  PowerShell's ConvertTo-Json array quirks can't corrupt it.
#  Run (or double-click build_feed_bunny.bat) after uploading clips.
# ============================================================
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

$cfg = Get-Content (Join-Path $root 'bunny_config.json') -Raw | ConvertFrom-Json
$cdn = $cfg.cdnHostname
if (-not $cdn) { Write-Host "ERROR: cdnHostname missing from bunny_config.json" -ForegroundColor Red; Read-Host "Enter to exit"; exit 1 }

$mapPath = Join-Path $root 'bunny_uploads.json'
if (-not (Test-Path $mapPath)) { Write-Host "ERROR: bunny_uploads.json not found. Upload clips first." -ForegroundColor Red; Read-Host "Enter to exit"; exit 1 }

# --- Robust read (tolerates an old {value:[...]} wrapped file) ---
$raw = Get-Content $mapPath -Raw | ConvertFrom-Json
if ($raw -isnot [array]) { $raw = @($raw) }
if ($raw.Count -gt 0 -and ($raw[0].PSObject.Properties.Name -contains 'value')) { $raw = $raw[0].value }
$records = @($raw)

function JStr($s) {
  if ($null -eq $s) { return 'null' }
  '"' + ($s.ToString() -replace '\\','\\\\' -replace '"','\"' -replace "`r","" -replace "`n",'\n') + '"'
}

$re = '^(?<film>.+?) \((?<year>\d{4})\)[^-]*- (?<s1>\d{2})\.(?<s2>\d{2})\.(?<s3>\d{2})-(?<e1>\d{2})\.(?<e2>\d{2})\.(?<e3>\d{2})\.\w+$'

$items = New-Object System.Collections.Generic.List[string]
$films = @{}
foreach ($r in $records) {
  if (-not $r.guid) { continue }
  $name  = [string]$r.file
  $film  = ([string]$r.folder) -replace '_clips$',''
  $year  = ''; $start = ''; $end = ''
  if ($name -match $re) {
    $film = $Matches.film; $year = $Matches.year
    $start = "$($Matches.s1):$($Matches.s2):$($Matches.s3)"
    $end   = "$($Matches.e1):$($Matches.e2):$($Matches.e3)"
  }
  $films[$film] = $true
  $url = "https://$cdn/$($r.guid)/playlist.m3u8"
  $items.Add("{""id"":$(JStr $r.guid),""file"":$(JStr $url),""film"":$(JStr $film),""year"":$(JStr $year),""start"":$(JStr $start),""end"":$(JStr $end)}")
}

$banner = "// AUTO-GENERATED by build_feed_bunny - do not edit by hand.`n// Streams from Bunny ($cdn). Regenerate after uploading new clips.`n"
$json = "[`n" + ($items -join ",`n") + "`n]"
Set-Content -Path (Join-Path $root 'videos.js') -Value ($banner + 'const VIDEOS=' + $json + ';') -Encoding UTF8

Write-Host ("Done. {0} clips across {1} films written to videos.js (streaming from {2})." -f $items.Count, $films.Count, $cdn) -ForegroundColor Green
