# Rebuilds videos.js from the film folders in this directory.
# Run this (or double-click rebuild_feed.bat) after adding new films.
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$exts = @('.mp4', '.mkv', '.webm', '.mov', '.m4v')
$re = '^(?<film>.+?) \((?<year>\d{4})\)[^-]*- (?<s1>\d{2})\.(?<s2>\d{2})\.(?<s3>\d{2})-(?<e1>\d{2})\.(?<e2>\d{2})\.(?<e3>\d{2})\.\w+$'

$entries = @()
Get-ChildItem -Path $root -Directory | Sort-Object Name | ForEach-Object {
    $dir = $_
    Get-ChildItem -Path $dir.FullName -File | Where-Object { $exts -contains $_.Extension.ToLower() } | Sort-Object Name | ForEach-Object {
        $film = $dir.Name -replace '_clips$', ''
        $year = ''; $start = ''; $end = ''
        if ($_.Name -match $re) {
            $film = $Matches.film
            $year = $Matches.year
            $start = "$($Matches.s1):$($Matches.s2):$($Matches.s3)"
            $end = "$($Matches.e1):$($Matches.e2):$($Matches.e3)"
        }
        $entries += [pscustomobject]@{
            file = "$($dir.Name)/$($_.Name)"
            film = $film
            year = $year
            start = $start
            end = $end
        }
    }
}

$json = $entries | ConvertTo-Json -Depth 3
if ($entries.Count -eq 1) { $json = "[$json]" }
$banner = "// AUTO-GENERATED by rebuild_feed - do not edit by hand.`n// Add films as folders of clips, then run rebuild_feed.bat to refresh.`n"
Set-Content -Path (Join-Path $root 'videos.js') -Value ($banner + 'const VIDEOS=' + $json + ';') -Encoding UTF8

Write-Host "Done. $($entries.Count) clips indexed across $((($entries | Select-Object -ExpandProperty film -Unique)).Count) films."
